### ISSUE TITLE
Is this intended for sharding or for LA with n-th identical clusters?

### ISSUE THREAD

**Issue by s3rj1k** [minio/sidekick#1]
Be sharding I mean a way to make some kind of strip/RAID0 on n-th clusters by balancing buckets, a way to overcome inability to horizontally scale `minio` cluster (no dynamic disk management)?

**Comment by harshavardhana** [comment]
No sharding just LB @s3rj1k

**Comment by s3rj1k** [comment]
@harshavardhana Thanks.
