### ISSUE TITLE
Sidekick unable to submit jobs to Minio cluster

### ISSUE THREAD

**Issue by mmonro** [minio/sidekick#10]
Spark jobs submitted to a minio cluster using sidekick began failing, when we turned logging on we observed the following errors in the sidekick container logs:

sidekick: Listening on :9000
http://host1:9000 is down : %!s(<nil>)
http://host2:9000 is down : %!s(<nil>)
http://host3:9000 is down : %!s(<nil>)
http://host4:9000 is down : %!s(<nil>)

We were able to manually submit jobs directly to all of the minio nodes fine so minio itself was working, but sidekick's basic host check wasn't functioning correctly.

Bouncing the minio services resolved the issue

**Comment by harshavardhana** [comment]
Added additional logging in 9a1e96d69d1ca1333efaa97bd94e82e5ee1deb79 - please check with the latest v0.1.5 release

**Comment by harshavardhana** [comment]
Closing this issue, as this has been figured out as a network issue.
