### ISSUE TITLE
Avoid unnecessary logging for TLS related spurious errors of io.EOF

### ISSUE THREAD

**Issue by harshavardhana** [minio/sidekick#107]
## Expected Behavior
No such logs.

## Current Behavior
```
Jun 06 22:22:37 xxxxxxx sidekick[3647762]: 2024/06/06 22:22:37 http: TLS handshake error from 10.20.103.9:50531: EOF
Jun 06 22:22:37 xxxxxxx sidekick[3647762]: 2024/06/06 22:22:37 http: TLS handshake error from 10.21.199.9:32391: EOF
Jun 06 22:22:38 xxxxxxx sidekick[3647762]: 2024/06/06 22:22:38 http: TLS handshake error from 10.20.135.13:11299: EOF
```

## Possible Solution
Check MinIO server implementation which implements a workaround by providing a custom

http.Server.ErrorLog (function) that discards the logs originating from net/http, we need
to turn this off otherwise these messages clobber up `--json` output in some environments.

**Comment by jiuker** [comment]
Have you a quickly steps to reproduce this?  @harshavardhana

**Comment by jiuker** [comment]
> you need to configure TLS on MinIO and TLS at sidekick and send a bunch of requests to sidekick using warp put

sidekick start with `--client-cert` and `--client-key` ?  @harshavardhana

**Comment by harshavardhana** [comment]
> `log.New(io.Discard, "", 0)` minio do that.

that is exactly what we need :-)
