### ISSUE TITLE
Cannot start sidekick in Windows Powershell

### ISSUE THREAD

**Issue by eco-minio** [minio/sidekick#12]
Launching sidekick via regular `cmd` terminal in Windows works, but trying to use the same command from PowerShell fails:

![image](https://user-images.githubusercontent.com/41090896/78837716-7ce46c00-79a9-11ea-872a-b927216a77ae.png)

**Comment by poornas** [comment]
```
./sidekick --health-path=/minio/health/ready --address :8000 "http://minio0{1...4}:9000"
```

Looks like powershell needs the endpoint to be double quoted.

**Comment by eco-minio** [comment]
Closing per above comment
