### ISSUE TITLE
FR - HTTPS with sidekick

### ISSUE THREAD

**Issue by eco-minio** [minio/sidekick#14]
Some applications (e.g., Veeam) require an https endpoint to be set, opening this feature request to see if we can implement https support for sidekick to allow it to be used with such applications.

**Comment by harshavardhana** [comment]
We can definitely implement HTTPS @eco-minio - we can use https://github.com/FiloSottile/mkcert to enable TLS automatically for localhost as well

**Comment by harshavardhana** [comment]
This is not the plan anymore as sidekick scope is restricted to being a sidecar load balancer.
