### ISSUE TITLE
Requests go to just one server

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/sidekick#19]
The request seems to go to just one server:
![2020-04-25-121321_950x184_scrot](https://user-images.githubusercontent.com/634494/80288682-5daa4600-86ee-11ea-9ce4-94d30891acbb.png)

**Comment by kalinon** [comment]
was there a resolution to this? I am seeing the same behavior.

**Comment by kalinon** [comment]
Ah. Putting more load on the sidekick (i.e. with warp) caused it to start sending it to others.
