### ISSUE TITLE
UI always shows 4 servers

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/sidekick#20]
Even when more than 4 servers are being load-balanced, the UI shows only 4 servers
I have attached the image where 6 servers are being load-balanced, shows only 4.
![2020-05-06-124640_948x188_scrot](https://user-images.githubusercontent.com/634494/81221587-e56a3d00-8f97-11ea-9e78-ade93c758cb7.png)

**Comment by harshavardhana** [comment]
This is fixed to some extent in #21 but we need a more generalized solution because of the static Rect() set for the UI.

**Comment by poornas** [comment]
Fixed by #22

**Comment by erfantkerfan** [comment]
> Even when more than 4 servers are being load-balanced, the UI shows only 4 servers I have attached the image where 6 servers are being load-balanced, shows only 4. ![2020-05-06-124640_948x188_scrot](https://user-images.githubusercontent.com/634494/81221587-e56a3d00-8f97-11ea-9e78-ade93c758cb7.png)

how you can start this UI? I found no doc about it, only a single gif in github page
@harshavardhana

**Comment by harshavardhana** [comment]
> > Even when more than 4 servers are being load-balanced, the UI shows only 4 servers I have attached the image where 6 servers are being load-balanced, shows only 4. ![2020-05-06-124640_948x188_scrot](https://user-images.githubusercontent.com/634494/81221587-e56a3d00-8f97-11ea-9e78-ade93c758cb7.png)
> 
> how you can start this UI? I found no doc about it, only a single gif in github page
> @harshavardhana 

This is only when you are running on a terminal. If you run it via container, or systemd it is automatically turned off.

**Comment by erfantkerfan** [comment]
> > > Even when more than 4 servers are being load-balanced, the UI shows only 4 servers I have attached the image where 6 servers are being load-balanced, shows only 4. ![2020-05-06-124640_948x188_scrot](https://user-images.githubusercontent.com/634494/81221587-e56a3d00-8f97-11ea-9e78-ade93c758cb7.png)
> > 
> > 
> > how you can start this UI? I found no doc about it, only a single gif in github page
> > @harshavardhana
> 
> This is only when you are running on a terminal. If you run it via container, or systemd it is automatically turned off.

actually, I'm using a systemd to run both minio and sidekick, it could be a nice feature so that you could see the stats even if I'm running a systemd

**Comment by harshavardhana** [comment]
> > > > Even when more than 4 servers are being load-balanced, the UI shows only 4 servers I have attached the image where 6 servers are being load-balanced, shows only 4. ![2020-05-06-124640_948x188_scrot](https://user-images.githubusercontent.com/634494/81221587-e56a3d00-8f97-11ea-9e78-ade93c758cb7.png)
> > > 
> > > 
> > > how you can start this UI? I found no doc about it, only a single gif in github page
> > > @harshavardhana
> > 
> > This is only when you are running on a terminal. If you run it via container, or systemd it is automatically turned off.
> 
> actually, I'm using a systemd to run both minio and sidekick, it could be a nice feature so that you could see the stats even if you are running a systemd 

Systemd doesn't have terminal you cannot pretty print there. 

What you are asking is not possible.
