### ISSUE TITLE
Add TLS

### ISSUE THREAD

**Issue by grzegorznowacki** [minio/sidekick#24]
It would be nice to have possibility to connect to sidekick using TLS, i.e. do something like `--address https://ADDRESS:PORT`. 

It would be useful when someone wants to use sidekick as standard reverse proxy with loadbalancing and put sidekick somewhere on server side (I know that it is intended to be used on client side). 

Now it is possible to put sidekick on server side but only connection between sidekick and Minio servers is encrypted. Connection between client and sidekick is plain text.

**Comment by harshavardhana** [comment]
sidekick is meant to be used on sidecar at localhost along with application, don't use it to replace nginx that is not it's purpose.
