### ISSUE TITLE
Ability to specfy ca-certificate

### ISSUE THREAD

**Issue by kvaps** [minio/sidekick#33]
**Is your feature request related to a problem? Please describe.**
Hi, I considering to use sidekick as proxy for kubernetes API servers. It would be nice to have an opportunity specify CAfile for the proxy

**Describe the solution you'd like**
The same as curl has:
```
     --cacert <file> CA certificate to verify peer against
     --capath <dir>  CA directory to verify peer against
```

optionaly also client certificate and key might be specified:
```
     --cert <certificate> Client certificate file.
     --key <key>     Private key file name
```

**Describe alternatives you've considered**

Alternatively the environment variables can be used.
See this commit which implements similar opportunity to another project https://github.com/piraeusdatastore/linstor-csi/commit/eb0b344c51b52f6b8138d5a990d9a1f7aa8b4d5a for example.

**Additional context**
Example usage:
```bash
sidekick --health-path=/healthz \
  --address 127.0.0.1:6443 \
  --cacert /etc/kubernetes/pki/ca.crt \
  https://kube-master{1..3}:6443
```

**Comment by harshavardhana** [comment]
Looks like a good idea, we shall add @kvaps - thanks for the feature request.
