### ISSUE TITLE
[faq]is sidekick cache read only cache, does it support write back or write through 

### ISSUE THREAD

**Issue by gwnet** [minio/sidekick#40]
is sidekick cache read only cache, does it support write back or write through 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`sidekick version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by poornas** [comment]
@gwnet , sidekick is a read only cache

**Comment by harshavardhana** [comment]
> @gwnet , sidekick is a read only cache

@gwnet sidekick is only meant for read only cache, we may do writes in future but it's not part of the plan yet.

**Comment by gwnet** [comment]
thank you so much!~
