### ISSUE TITLE
terminal gui site header shows 1st for all hosts

### ISSUE THREAD

**Issue by karlpokus** [minio/sidekick#45]
The terminal gui site header shows 1st for all hosts even though I'm running multiple sites and passed `http://minio{1...2}:9000,http://minio{3...4}:9000` to sidekick.

## Expected Behavior

Line 1 and 2 should say 1st and line 3 and 4 should say 2nd

## Current Behavior

All hosts are 1st

## Steps to Reproduce (for bugs)

1. run 4 minio servers w `minio server http://minio{1...2}/data{1...2} http://minio{3...4}/data{3...4}`
2. then run sidekick w `minio/sidekick:v0.5.1 --health-path=/minio/health/ready http://minio{1...2}:9000,http://minio{3...4}:9000` and include `-it` to display the sidekick terminal gui.

## Context

I'm heartbroken :) No, I just think the host should show the correct site.

## Regression

I don't know.

## Your Environment

* Version used (`sidekick version`): sidekick:v0.5.1
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`): mac os catalina 10.15.5
* Link to your project: https://github.com/karlpokus/minio-lab

**Comment by poornas** [comment]
@karlpokus , to start sidekick for multisites - there should be a space between site1 and site2, not a comma. 
your command would be
```
minio/sidekick:v0.5.1 --health-path=/minio/health/ready http://minio{1...2}:9000 http://minio{3...4}:9000
```

**Comment by harshavardhana** [comment]
> @karlpokus , to start sidekick for multisites - there should be a space between site1 and site2, not a comma.
> your command would be
> 
> ```
> minio/sidekick:v0.5.1 --health-path=/minio/health/ready http://minio{1...2}:9000 http://minio{3...4}:9000
> ```

Closing as per this comment.
