### ISSUE TITLE
Spark orchestrator instead of operator?

### ISSUE THREAD

**Issue by antonwnk** [minio/sidekick#53]
Hi. The title already summarises everything. I believe the README wrongly refers to the Spark Operator as the Spark Orchestrator a couple of times.
Sorry if I'm mistaken though. I will do a PR as soon as anyone confirms this should be done.
The doc should be updated altogether, with the spark-operator being out of the Helm incubator now, but I wouldn't venture at that.

**Comment by harshavardhana** [comment]
Spark operator in hindsight is an orchestration scheduler, so it isn't wrong to say that. Nonetheless updated the REAMDE.md for brevity.
