### ISSUE TITLE
could sidekick support different path to route different minio cluster？

### ISSUE THREAD

**Issue by lddlww** [minio/sidekick#60]
reference to sidekick SITE flag：
```
SITE:
  Each SITE is a comma separated list of pools of that site: http://172.17.0.{2...5},http://172.17.0.{6...9}.
  If all servers in SITE1 are down, then the traffic is routed to the next site - SITE2.
```
as above mention，SITEs are mirror of each other，however when i have different backend minio cluster，does one sidekick support use difference path to route different minio cluster？do not use difference port to implement it

**Comment by harshavardhana** [comment]
No, it is meant to be purpose-driven the way it is implemented today is the maximum scope of this project, it's not meant routing based on custom path's - it is not a generic LB it is meant to be used with MinIO deployments.
