### ISSUE TITLE
virtual-host requests

### ISSUE THREAD

**Issue by s7thamon** [minio/sidekick#63]
Is it possible to use sidekick with virtual-host-style requests? This is outlined under the Domain section in https://docs.min.io/docs/minio-server-configuration-guide.html

Unfortunately using synology in an attempt to backup to minio via sidekick is not cooperating without this functionality. DNS records have been setup for the wildcard CNAME but still unable to get this to work.

**Comment by harshavardhana** [comment]
You can run sidekick to do whatever way you want. It will preserve the incoming Host header as long as your backend S3 service supports virtual host style.

Given that you can make relevant changes to your DNS to route your requests to sidekick appropriately it will work fine.
