### ISSUE TITLE
Can sidekick get all the pods automatically from kubernetes selector?

### ISSUE THREAD

**Issue by kesavkolla** [minio/sidekick#65]
I have installed minio in kubernetes cluster. By default the minio operator creates all the minio pods and then setsup a service with pod selection rule. Is it possible to leverage the kubernetes selector to get all the POD IPs?

**Comment by harshavardhana** [comment]
sidekick is a standalone binary with no dependency on k8s APIs - sidekick must be provided the relevant headless service names that you wish to load balance.
