### ISSUE TITLE
Configuring multiple pools cannot support read requests

### ISSUE THREAD

**Issue by Hintic** [minio/sidekick#80]
The sidekick running on the current server is as follows:
` sidekick --health-path=/minio/health/ready http://site1-minio{1...4}:9000,http://site1-minio{5...8}:9000`

## Current Behavior

1. I create buckets with the same name in two sets of clusters, and then configure them into a list of pools in sidekick。
2. When sending an `upload` request through this sidekick, I found that the stored files will be roughly divided into two pools, but when I call the `statObject` or `download` request, I find that sometimes I can get `200` successfully, and sometimes I can’t get `404`.

## Possible Solution
Does this mean that sidekick only supports request sharing among multiple pools, regardless of whether it is read or write?

## My Environment
cache: `enabled`
version: `sidekick:2.0.8`

**Comment by harshavardhana** [comment]
sidekick is not meant to combine two different clusters, you need first a cluster of MinIO with two pools.

Those pools are specified to sidekick via comma separated liar.

**Comment by Hintic** [comment]
In addition, I would like to ask a small question. Can a cluster of MinIO with two pools be created in K8S without an Operator? Is there any relevant information?

**Comment by harshavardhana** [comment]
> In addition, I would like to ask a small question. Can a cluster of MinIO with two pools be created in K8S without an Operator? Is there any relevant information?

We only recommend the operator, of course, you can do it without an operator as well - but that is not what we document or recommend, or test. You are on your own if you want to not use the Operator. @Hintic
