### ISSUE TITLE
Does Sidekick support multi-replicas through deployment in K8S?

### ISSUE THREAD

**Issue by Hintic** [minio/sidekick#86]
I uploaded the [official image](https://hub.docker.com/r/minio/sidekick) to the local, deployed it through deployment in K8S, and the replicas was 4.

## Expected Behavior
All sidekick pods can provide services normally, and output trace logs of health detection and application.

## Current Behavior
Some container processes in sidekick pods（sometimes 2, sometimes 3,  not fixed） only output `listen: 9000` logs and get stuck，these processes handle some S3 requests to get objects and return empty.

## Possible Solution
So, in the K8S, how to deploy multiple replicas of sidekick separately through deployment, or as a sidecar container? Or use statefulset for that?

## Your Environment
* Version used (`sidekick version`): latest 3.0.2
* Environment name and version: K8S 1.8

**Comment by harshavardhana** [comment]
Yes you can create a single cluster IP with multiple sidekick instances.

Sidekick is designed to run as a d
Sidecar container to your application pod, so there is point running it centrally like nginx.

So use it accordingly.
