### ISSUE TITLE
Had sidekick's cache feature been removed? 

### ISSUE THREAD

**Issue by SAILgaosai** [minio/sidekick#87]
I saw that you have removed the cache from README.md in commit on April 19
what should i do, if i need?

**Comment by harshavardhana** [comment]
sidekick caching was complicated and had no real benefits in reality. So we removed it to keep the code cleaner and stable.

**Comment by SAILgaosai** [comment]
So is there any cache solution here for minio? if I want to use SSD to accelerate repeatedly read.

**Comment by harshavardhana** [comment]
> So is there any cache solution here for minio? if I want to use SSD to accelerate repeatedly read.

No there is none @SAILgaosai use SSD directly with MinIO.
