### ISSUE TITLE
HTTP 499 err when update files with --disable-multipart 

### ISSUE THREAD

**Issue by SAILgaosai** [minio/sidekick#88]
I use mc mirror --disable-multipart <minio1> <minio2> 
the logs are both 200 OK in sidekick console output
BUT there are many HTTP 499 error in minio logs （I use mc admin trace to monitor）
the result is the object PUT with  HTTP 499 transfer failed

In the end I had to switch back to nginx load balancer and it worked fine

I was wondering if he has some http client_max_body_size limit ?
but I didn't find related configuration items in the program description

**Comment by harshavardhana** [comment]
There is no such thing, I think there is a timeout that is set which might be premature.

**Comment by harshavardhana** [comment]
This may be outside of sidekick directly on the backend issue.
